controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

redirect:
    path: /redirect
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /home

external:
    path: /external
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: https://www.youtube.com/watch?v=yJZQkEXZvbs